### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by jamal2362**

### CODE REVIEW

**Comment by xboxfanj** [comment]
Thanks @jamal2362.  Can you push this to gerrit.aospa.co?  We can't merge pull requests because the gerrit sync is only one-way.

**Comment by jamal2362** [comment]
Hey Jake
I have never worked with Gerrit before. So I wouldn't know how to open a pull-request there. If you want you can also add it to gerrit.

I always get a permission issue on from gerrit when I push the change.

**Comment by jamal2362** [comment]
remote: Resolving deltas: 100% (2/2)
remote: error: branch refs/heads/topaz:
remote: Push to refs/for/topaz to create a review, or get 'Push' rights to update the branch.
remote: User: jamal2362
remote: Contact an administrator to fix the permissions
remote: Processing changes: refs: 1, done    
To ssh://gerrit.aospa.co:29418/AOSPA/android_packages_apps_ParanoidGlyph
 ! [remote rejected] HEAD -> topaz (prohibited by Gerrit: not permitted: update)
error: Error sending some references after 'ssh://gerrit.aospa.co:29418/AOSPA/android_packages_apps_ParanoidGlyph'

**Comment by jamal2362** [comment]
> Thanks @jamal2362. Can you push this to gerrit.aospa.co? We can't merge pull requests because the gerrit sync is only one-way.

Done 👍🏽

**Pull request closed without merging**
